# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 11:55
from __future__ import unicode_literals

import conflicto.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=conflicto.models.generate_uuid, max_length=63, unique=True)),
                ('post_uuid', models.CharField(max_length=63)),
                ('comment', models.TextField()),
                ('type', models.CharField(choices=[('SUPPORT', 'SUPPORT'), ('CONFLICT', 'CONFLICT'), ('REPORT', 'REPORT')], max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reports', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('endorse', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FBProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('fb_link', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('dp_link', models.CharField(max_length=255, null=True)),
                ('cover_link', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=conflicto.models.generate_uuid, max_length=63, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(db_index=True, max_length=255, null=True)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('shared_post', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reports', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('endorse', models.IntegerField(default=0)),
                ('supports', models.IntegerField(default=0)),
                ('conflicts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_uuid', models.CharField(db_index=True, max_length=63)),
                ('action', models.CharField(choices=[('LIKE', 'LIKE'), ('DISLIKE', 'DISLIKE'), ('SUPPORT', 'SUPPORT'), ('CONFLICT', 'CONFLICT'), ('REPORT', 'REPORT'), ('ENDORSE', 'ENDORSE')], db_index=True, max_length=255)),
                ('object_type', models.CharField(choices=[('POST', 'POST'), ('COMMENT', 'COMMENT')], db_index=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=conflicto.models.generate_uuid, max_length=63, unique=True)),
                ('fcm_token', models.CharField(max_length=255, null=True)),
                ('firebase_id', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='conflicto.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['object_uuid', 'action', 'object_type', 'user_id'], name='conflicto_r_object__242a40_idx'),
        ),
    ]
