# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conflicto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reactions',
        ),
    ]
