# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflicto', '0002_auto_20170507_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='object_uuid',
            field=models.CharField(db_index=True, max_length=63),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['object_uuid', 'action', 'object_type', 'user_id'], name='conflicto_r_object__242a40_idx'),
        ),
    ]
