# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 19:17
from __future__ import unicode_literals

import conflicto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflicto', '0002_auto_20170520_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbprofile',
            name='uuid',
            field=models.CharField(db_index=True, default=conflicto.models.generate_uuid, max_length=63, unique=True),
        ),
    ]
